import { db } from "./index";
import {
  users,
  leads,
  followups,
  visits,
  activities,
  photos,
} from "./schema";

async function seed() {
  console.log("Seeding database...");

  const [user] = await db
    .insert(users)
    .values({
      clerkId: "seed_user_001",
      name: "Rahul Sharma",
      email: "rahul@rmcconcrete.com",
      phone: "+91-9876543210",
      company: "RMC Concrete Solutions",
      role: "sales_manager",
    })
    .returning();

  const leadData: (typeof leads.$inferInsert)[] = [
    {
      userId: user.id,
      companyName: "BuildRight Constructions",
      clientCompany: "BuildRight Constructions Pvt Ltd",
      builderName: "Suresh Reddy",
      projectName: "Green Valley Apartments",
      contactPerson: "Suresh Reddy",
      designation: "Project Director",
      mobile: "+91-9876543211",
      email: "suresh@buildright.com",
      siteAddress: "Plot 42, Phase 3, HITEC City",
      city: "Hyderabad",
      district: "Ranga Reddy",
      state: "Telangana",
      pincode: "500081",
      latitude: "17.4435",
      longitude: "78.3772",
      existingVendor: "UltraTech RMC",
      competitorNotes: "Offering 5% discount on bulk orders",
      remarks: "High potential project, multiple towers",
      stage: "negotiation",
      leadScore: 85,
      projectType: "residential",
      projectStatus: "foundation",
      estimatedValue: "25000000",
      numberOfFloors: 16,
      builtUpArea: "48000",
      estimatedM3: "8500",
      monthlyM3: "1200",
      immediateM3: "500",
      gradeRequirements: ["M20", "M25", "M30"],
      expectedSupplyDate: "2026-07-01",
    },
    {
      userId: user.id,
      companyName: "InfraCore Developers",
      clientCompany: "InfraCore Developers & Engineers",
      builderName: "Amit Patel",
      projectName: "Skyline Business Park",
      contactPerson: "Amit Patel",
      designation: "Managing Director",
      mobile: "+91-9876543212",
      email: "amit@infracore.in",
      siteAddress: "Sector 62, Golf Course Road",
      city: "Gurugram",
      district: "Gurugram",
      state: "Haryana",
      pincode: "122011",
      latitude: "28.5022",
      longitude: "77.0789",
      existingVendor: "",
      competitorNotes: "No existing supplier for this project",
      remarks: "New client, needs technical consultation",
      stage: "meeting_scheduled",
      leadScore: 70,
      projectType: "commercial",
      projectStatus: "excavation",
      estimatedValue: "18000000",
      numberOfFloors: 12,
      builtUpArea: "35000",
      estimatedM3: "6200",
      monthlyM3: "800",
      immediateM3: "300",
      gradeRequirements: ["M25", "M30", "M40"],
      expectedSupplyDate: "2026-08-15",
    },
    {
      userId: user.id,
      companyName: "Nandi Infrastructures",
      clientCompany: "Nandi Infrastructures Ltd",
      builderName: "Venkatesh Rao",
      projectName: "Industrial Shed Complex - Plot 7A",
      contactPerson: "Venkatesh Rao",
      designation: "CEO",
      mobile: "+91-9876543213",
      email: "venkatesh@nandiinfra.com",
      siteAddress: "Industrial Development Area, KIADB",
      city: "Bengaluru",
      district: "Bengaluru Urban",
      state: "Karnataka",
      pincode: "560066",
      latitude: "12.9352",
      longitude: "77.6245",
      existingVendor: "ACC RMC",
      competitorNotes: "ACC has quality issues, we can offer better",
      remarks: "Price sensitive but volume is high",
      stage: "quotation_sent",
      leadScore: 60,
      projectType: "industrial",
      projectStatus: "planning",
      estimatedValue: "12000000",
      numberOfFloors: 2,
      builtUpArea: "22000",
      estimatedM3: "3800",
      monthlyM3: "600",
      immediateM3: "200",
      gradeRequirements: ["M15", "M20", "M25"],
      expectedSupplyDate: "2026-09-01",
    },
    {
      userId: user.id,
      companyName: "Coastal Engineering Corp",
      clientCompany: "Coastal Engineering Corporation",
      builderName: "Michael D'Souza",
      projectName: "Harbor View Residency",
      contactPerson: "Michael D'Souza",
      designation: "Technical Director",
      mobile: "+91-9876543214",
      email: "michael@coastaleng.com",
      siteAddress: "Beach Road, Near Lighthouse",
      city: "Chennai",
      district: "Chennai",
      state: "Tamil Nadu",
      pincode: "600004",
      latitude: "13.0408",
      longitude: "80.2778",
      existingVendor: "Ramco RMC",
      competitorNotes: "Loyalty contract with Ramco for 3 years",
      remarks: "Difficult to break existing contract",
      stage: "lost",
      leadScore: 40,
      projectType: "residential",
      projectStatus: "structural",
      estimatedValue: "15000000",
      numberOfFloors: 10,
      builtUpArea: "28000",
      estimatedM3: "5200",
      monthlyM3: "900",
      immediateM3: "0",
      gradeRequirements: ["M20", "M30", "M35"],
      expectedSupplyDate: null,
      lostReason: "Existing long-term contract with competitor",
    },
    {
      userId: user.id,
      companyName: "Green Earth Builders",
      clientCompany: "Green Earth Builders & Developers",
      builderName: "Priya Sharma",
      projectName: "Eco Villas - Phase 2",
      contactPerson: "Priya Sharma",
      designation: "Owner",
      mobile: "+91-9876543215",
      email: "priya@greenearth.in",
      siteAddress: "Wagholi, Pune",
      city: "Pune",
      district: "Pune",
      state: "Maharashtra",
      pincode: "412207",
      latitude: "18.5913",
      longitude: "73.9843",
      existingVendor: "",
      competitorNotes: "No competition yet, first supplier to reach out",
      remarks: "Environmentally conscious, interested in green concrete",
      stage: "site_visited",
      leadScore: 75,
      projectType: "residential",
      projectStatus: "foundation",
      estimatedValue: "8000000",
      numberOfFloors: 4,
      builtUpArea: "15000",
      estimatedM3: "2800",
      monthlyM3: "400",
      immediateM3: "150",
      gradeRequirements: ["M20", "M25"],
      expectedSupplyDate: "2026-06-15",
    },
  ];

  const createdLeads = await db.insert(leads).values(leadData).returning();
  console.log(`Created ${createdLeads.length} leads`);

  const followupData = [
    {
      leadId: createdLeads[0].id,
      userId: user.id,
      followupDate: "2026-06-10",
      followupTime: "10:30:00",
      type: "meeting" as const,
      priority: "high" as const,
      status: "completed" as const,
      notes: "Discussed pricing for M30 grade. Client wants sample testing.",
      completedAt: new Date("2026-06-10T12:00:00Z"),
    },
    {
      leadId: createdLeads[0].id,
      userId: user.id,
      followupDate: "2026-06-14",
      followupTime: "15:00:00",
      type: "call" as const,
      priority: "high" as const,
      status: "pending" as const,
      notes: "Follow up on sample test results and negotiate pricing",
    },
    {
      leadId: createdLeads[0].id,
      userId: user.id,
      followupDate: "2026-06-18",
      followupTime: "11:00:00",
      type: "whatsapp" as const,
      priority: "medium" as const,
      status: "pending" as const,
      notes: "Send M30 test report and revised quotation",
    },
    {
      leadId: createdLeads[1].id,
      userId: user.id,
      followupDate: "2026-06-12",
      followupTime: "09:00:00",
      type: "meeting" as const,
      priority: "high" as const,
      status: "pending" as const,
      notes: "Site meeting to understand requirements and give technical presentation",
    },
    {
      leadId: createdLeads[2].id,
      userId: user.id,
      followupDate: "2026-06-09",
      followupTime: "14:30:00",
      type: "call" as const,
      priority: "high" as const,
      status: "completed" as const,
      notes: "Sent quotation for M15-M25 grades. Client reviewing.",
      completedAt: new Date("2026-06-09T15:00:00Z"),
    },
    {
      leadId: createdLeads[2].id,
      userId: user.id,
      followupDate: "2026-06-16",
      followupTime: "11:30:00",
      type: "email" as const,
      priority: "medium" as const,
      status: "pending" as const,
      notes: "Follow up on quotation status and address any concerns",
    },
    {
      leadId: createdLeads[4].id,
      userId: user.id,
      followupDate: "2026-06-08",
      followupTime: "10:00:00",
      type: "call" as const,
      priority: "high" as const,
      status: "completed" as const,
      notes: "Post site visit follow-up. Client interested in eco-friendly concrete mix.",
      completedAt: new Date("2026-06-08T10:30:00Z"),
    },
    {
      leadId: createdLeads[4].id,
      userId: user.id,
      followupDate: "2026-06-13",
      followupTime: "16:00:00",
      type: "meeting" as const,
      priority: "high" as const,
      status: "pending" as const,
      notes: "Present green concrete proposal and pricing",
    },
  ];

  await db.insert(followups).values(followupData);
  console.log(`Created ${followupData.length} followups`);

  const visitData = [
    {
      leadId: createdLeads[0].id,
      userId: user.id,
      checkInTime: new Date("2026-06-01T09:15:00Z"),
      checkOutTime: new Date("2026-06-01T11:45:00Z"),
      checkInLat: "17.4435",
      checkInLng: "78.3772",
      checkInAddress: "Green Valley Apartments, HITEC City, Hyderabad",
      checkOutLat: "17.4440",
      checkOutLng: "78.3780",
      durationMinutes: 150,
      notes: "Site visit to assess foundation work progress. Meeting with project engineer.",
    },
    {
      leadId: createdLeads[4].id,
      userId: user.id,
      checkInTime: new Date("2026-06-05T14:00:00Z"),
      checkOutTime: new Date("2026-06-05T16:30:00Z"),
      checkInLat: "18.5913",
      checkInLng: "73.9843",
      checkInAddress: "Eco Villas Phase 2, Wagholi, Pune",
      checkOutLat: "18.5918",
      checkOutLng: "73.9849",
      durationMinutes: 150,
      notes: "Site assessment for Phase 2. Checked slab work and discussed concrete requirements for next 2 floors.",
    },
    {
      leadId: createdLeads[1].id,
      userId: user.id,
      checkInTime: new Date("2026-06-03T10:00:00Z"),
      checkOutTime: new Date("2026-06-03T12:00:00Z"),
      checkInLat: "28.5022",
      checkInLng: "77.0789",
      checkInAddress: "Skyline Business Park, Sector 62, Gurugram",
      checkOutLat: "28.5028",
      checkOutLng: "77.0795",
      durationMinutes: 120,
      notes: "Preliminary site survey. Excavation in progress. Discussed technical specs.",
    },
  ];

  await db.insert(visits).values(visitData);
  console.log(`Created ${visitData.length} visits`);

  const activityData = [
    {
      leadId: createdLeads[0].id,
      userId: user.id,
      type: "lead_created" as const,
      description: "Lead created from referral by existing client",
    },
    {
      leadId: createdLeads[0].id,
      userId: user.id,
      type: "stage_changed" as const,
      description: "Stage changed from new to contacted",
      metadata: { fromStage: "new", toStage: "contacted" },
    },
    {
      leadId: createdLeads[0].id,
      userId: user.id,
      type: "visit" as const,
      description: "Site visit completed at Green Valley Apartments",
    },
    {
      leadId: createdLeads[0].id,
      userId: user.id,
      type: "stage_changed" as const,
      description: "Stage changed from site_visited to negotiation",
      metadata: { fromStage: "site_visited", toStage: "negotiation" },
    },
    {
      leadId: createdLeads[3].id,
      userId: user.id,
      type: "lost" as const,
      description: "Lost to competitor - existing contract with Ramco RMC",
      metadata: { lostReason: "Existing long-term contract with competitor" },
    },
    {
      leadId: createdLeads[4].id,
      userId: user.id,
      type: "lead_created" as const,
      description: "Lead created from trade show inquiry",
    },
    {
      leadId: createdLeads[4].id,
      userId: user.id,
      type: "visit" as const,
      description: "Site visit at Eco Villas Phase 2",
    },
  ];

  await db.insert(activities).values(activityData);
  console.log(`Created ${activityData.length} activities`);

  const photoData = [
    {
      leadId: createdLeads[0].id,
      userId: user.id,
      url: "https://placehold.co/800x600/EEE/999?text=Site+Photo+1",
      fileName: "site_photo_1.jpg",
      fileSize: 245000,
      type: "site" as const,
      caption: "Foundation work in progress - Tower A",
    },
    {
      leadId: createdLeads[0].id,
      userId: user.id,
      url: "https://placehold.co/800x600/EEE/999?text=Site+Photo+2",
      fileName: "site_photo_2.jpg",
      fileSize: 312000,
      type: "site" as const,
      caption: "Steel reinforcement - Tower B",
    },
    {
      leadId: createdLeads[4].id,
      userId: user.id,
      url: "https://placehold.co/800x600/EEE/999?text=Project+Photo",
      fileName: "project_photo_1.jpg",
      fileSize: 189000,
      type: "project" as const,
      caption: "Phase 2 construction overview",
    },
    {
      leadId: createdLeads[1].id,
      userId: user.id,
      url: "https://placehold.co/800x600/EEE/999?text=Visiting+Card",
      fileName: "visiting_card_amit.jpg",
      fileSize: 56000,
      type: "visiting_card" as const,
      caption: "Amit Patel - Managing Director",
    },
  ];

  await db.insert(photos).values(photoData);
  console.log(`Created ${photoData.length} photos`);

  console.log("Seeding complete!");
}

seed()
  .catch((e) => {
    console.error("Seeding failed:", e);
    process.exit(1);
  })
  .then(() => process.exit(0));
